name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so that annotate_pr_with_ruff can access it.
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install ruff from PyPI
        uses: install-pinned/ruff@66c987de12929f701b73e83c82edc36050ae55a0
      - name: Install requests library
        run: pip install requests==2.28.1
        shell: bash
      - name: annotate_pr_with_ruff
        uses: EnriqueSoria/annotate_pr_with_ruff@89c9bfd42dfbeec31044f61fe52ffeac1c5e52c4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print changelog
        run: echo ${{ steps.annotate_pr_with_ruff.outputs.stdout }}
