name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so that typilus can access it.
      - uses: actions/checkout@v2
      - name: PR annotator with ruff
        uses: EnriqueSoria/annotate_pr_with_ruff@v0.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
