name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so that annotate_pr_with_ruff can access it.
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install ruff from PyPI
        uses: install-pinned/ruff@66c987de12929f701b73e83c82edc36050ae55a0
      - name: PR annotator with ruff
        uses: EnriqueSoria/annotate_pr_with_ruff@v0.1.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
